version: "3.8"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 1100:80 # map port 1100 on host to port 80 on container
    env_file:
      - ".env" # load environment variables from .env file
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 1101:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 1102:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306